# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eloi et Marie
email: thi.suzanne@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site du mariage d'Eloi et Marie
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://site-mariage.github.io/site-mariage-EloiEtMarie/" # the base hostname & protocol for your site
github_username:  thizanne

# Build settings
markdown: kramdown

# Global variables
url-liste: https://www.millemercismariage.com/eloietmarie27aout/liste.html
prestataire-liste: "Mille Mercis"
